name: chart-unit
version: '0.6.0.0'
synopsis: Native haskell charts.
description: ! '

  <<https://tonyday567.github.io/other/mainExample.svg>>


  chart-unit is a native haskell charting library designed:


  - as a chart DSL and algebra


  - towards a minimalist look and feel


  - to provide a set of default values that are robust across differet data and physical
  chart scales


  - around provision of a small but core set of chart types.


  See <https://tonyday567.github.io/chart-unit/index.html chart-unit> for a chart
  gallery.

'
category: charts
author: Tony Day
maintainer: tonyday567@gmail.com
copyright: 2016 Tony Day
license: BSD3
github: tonyday567/chart-unit
extra-source-files:
- stack.yaml
- other/*.svg
dependencies:
- base >=4.7 && <5
- generic-lens >= 0.5.2.0
- lens
- numhask
- numhask-range
library:
  source-dirs: src
  ghc-options:
  - -funbox-strict-fields
  - -fforce-recomp
  exposed-modules:
  - Chart
  - Chart.ADT
  - Chart.Arrow
  - Chart.Bar
  - Chart.Core
  - Chart.Data
  - Chart.Data.Time
  - Chart.Glyph
  - Chart.Hud
  - Chart.Line
  - Chart.Rect
  - Chart.Text
  dependencies:
  - SVGFonts
  - colour
  - data-default
  - diagrams-lib
  - diagrams-svg
  - foldl
  - formatting
  - linear
  - palette
  - protolude
  - scientific
  - text
  - time
  default-extensions:
    - DeriveGeneric
    - DeriveTraversable
    - FlexibleContexts
    - FlexibleInstances
    - InstanceSigs
    - MultiParamTypeClasses
    - NegativeLiterals
    - NoImplicitPrelude
    - OverloadedStrings
    - PatternSynonyms
    - RankNTypes
    - TypeFamilies
    - UnicodeSyntax
executables:
  chart-unit-main-example:
    main: mainExample.hs
    source-dirs: examples
    ghc-options:
    - -funbox-strict-fields
    - -fforce-recomp
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chart-unit
  chart-unit-source-examples:
    main: sourceExamples.hs
    source-dirs: examples
    ghc-options:
    - -funbox-strict-fields
    - -fforce-recomp
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chart-unit
    - diagrams-lib
    - protolude
    - text
  chart-unit-gallery:
    main: gallery.hs
    source-dirs: examples
    ghc-options:
    - -funbox-strict-fields
    - -fforce-recomp
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chart-unit
    - diagrams-lib
    - formatting
    - mwc-probability
    - mwc-random
    - numhask-histogram
    - primitive
    - protolude
    - text
    - time
tests:
  test:
    main: test.hs
    source-dirs: test
    dependencies:
    - chart-unit
    - doctest
    - tasty
    - tasty-hspec
