resolver: lts-7.19

packages:
- '.'
- location:
    git: https://github.com/tonyday567/tower.git
    commit: ff36e3028c84d45329b6dc928150f317e598ee1c
  extra-dep: true
- location:
    git: https://github.com/dequbed/polynomial.git
    commit: 8f78235e6fe6e34624547e25049e916ad4c6e401
  extra-dep: true

extra-deps:
- erf-native-1.0.0.1
- polynomial-0.7.2
