resolver: nightly-2018-06-05

packages:
  - .

extra-deps:
  - generic-lens-labels-0.1.0.2
  - numhask-histogram-0.1.2.1
  # - numhask-0.2.0.0
  # - numhask-prelude-0.0.3.0
  # - numhask-range-0.2.1.0
  # - mwc-probability-2.0.2

allow-newer: true
