resolver: nightly-2018-06-05

packages:
  - .

extra-deps:
  - generic-lens-labels-0.1.0.2
  - SVGFonts-1.7
  - diagrams-lib-1.4.2.3
  - diagrams-svg-1.4.2
  - github: tonyday567/numhask
    commit: 06f4cb735871dc3d7efe54b8827340bcb9d1efa4
    subdirs:
      - numhask
      - numhask-prelude
      - numhask-hedgehog
  - github: tonyday567/numhask-range
    commit: 2e3c655c3e23a314f17115de0edb96a8421d7373
    subdirs:
      - numhask-range
      - numhask-histogram

allow-newer: true
